export class UserDTO {
  type: string;
  business_cd: string;
  user_cd: string;
  user_uuid: string;
  user_nm: string;
  user_birth: string;
  user_id: string;
  is_user_id: boolean;
  user_pwd: string;
  user_pwd_chk: string;
  new_user_pwd: string;
  new_user_pwd_chk: string;
  user_regno: string;
  is_user_regno: boolean;

  user_hpno: string;
  user_hpno_new: string;
  is_user_hpno: boolean;

  user_email: string;
  user_email_new: string;
  is_user_email: boolean;

  corp_type: string;
  corp_nm: string;
  corp_ceo_nm: string;
  corp_bnno: string;
  corp_cnno: string;
  corp_telno: string;
  corp_telno1: string;
  corp_telno2: string;
  corp_telno3: string;
  corp_faxno: string;
  corp_faxno1: string;
  corp_faxno2: string;
  corp_faxno3: string;
  corp_cust_nm: string;
  corp_cust_hpno: string;
  corp_cust_email: string;
  corp_region_cd: string;
  corp_region_nm: string;
  is_corp_cust_email: boolean;
  corp_post: string;
  corp_addr: string;
  corp_addr_dtl: string;
  recv_email_yn: string;
  agr1_yn: string;
  agr2_yn: string;
  agr3_yn: string;
  agr4_yn: string;
  active_yn: string;
  agr_all_yn: string;
  status_cd: string;
  business_cd_nm: string;
  status_cd_nm: string;
  user_cd_nm: string;
  corp_region_cd_nm: string;
  created_at: string;
  login_fail_cnt: number;
  login_block_yn: string;
  user_pwd_chg_at: string;
  created_ip: string;
  created_id: string;
  updated_ip: string;
  updated_id: string;
  auth_code: string;

  constructor(data: Partial<UserDTO> = {}) {
    this.type = data.type || '';
    this.business_cd = data.business_cd || '';
    this.user_cd = data.user_cd || '';
    this.user_uuid = data.user_uuid || '';
    this.user_nm = data.user_nm || '';
    this.user_birth = data.user_birth || '';
    this.user_id = data.user_id || '';
    this.is_user_id = data.is_user_id || false;
    this.user_pwd = data.user_pwd || '';
    this.user_pwd_chk = data.user_pwd_chk || '';
    this.new_user_pwd = data.new_user_pwd || '';
    this.new_user_pwd_chk = data.new_user_pwd_chk || '';
    this.user_regno = data.user_regno || '';
    this.is_user_regno = data.is_user_regno || false;
    this.user_hpno = data.user_hpno || '';
    this.user_hpno_new = data.user_hpno_new || '';
    this.is_user_hpno = data.is_user_hpno || false;
    this.user_email = data.user_email || '';
    this.user_email_new = data.user_email_new || '';
    this.is_user_email = data.is_user_email || false;
    this.corp_type = data.corp_type || '';
    this.corp_nm = data.corp_nm || '';
    this.corp_ceo_nm = data.corp_ceo_nm || '';
    this.corp_bnno = data.corp_bnno || '';
    this.corp_cnno = data.corp_cnno || '';
    this.corp_telno = data.corp_telno || '';
    this.corp_telno1 = data.corp_telno1 || '';
    this.corp_telno2 = data.corp_telno2 || '';
    this.corp_telno3 = data.corp_telno3 || '';
    this.corp_faxno = data.corp_faxno || '';
    this.corp_faxno1 = data.corp_faxno1 || '';
    this.corp_faxno2 = data.corp_faxno2 || '';
    this.corp_faxno3 = data.corp_faxno3 || '';
    this.corp_cust_nm = data.corp_cust_nm || '';
    this.corp_cust_hpno = data.corp_cust_hpno || '';
    this.corp_cust_email = data.corp_cust_email || '';
    this.is_corp_cust_email = data.is_corp_cust_email || false;
    this.corp_post = data.corp_post || '';
    this.corp_addr = data.corp_addr || '';
    this.corp_addr_dtl = data.corp_addr_dtl || '';
    this.corp_region_cd = data.corp_region_cd || '';
    this.corp_region_nm = data.corp_region_nm || '';
    this.recv_email_yn = data.recv_email_yn || '';
    this.agr1_yn = data.agr1_yn || '';
    this.agr2_yn = data.agr2_yn || '';
    this.agr3_yn = data.agr3_yn || '';
    this.agr4_yn = data.agr4_yn || '';
    this.active_yn = data.agr4_yn || '';
    this.agr_all_yn = data.agr_all_yn || '';
    this.status_cd = data.status_cd || '';
    this.business_cd_nm = data.business_cd_nm || '';
    this.status_cd_nm = data.status_cd_nm || '';
    this.user_cd_nm = data.user_cd_nm || '';
    this.corp_region_cd_nm = data.corp_region_cd_nm || '';
    this.created_at = data.created_at || '';
    this.login_fail_cnt = data.login_fail_cnt || 0;
    this.login_block_yn = data.login_block_yn || '';
    this.user_pwd_chg_at = data.user_pwd_chg_at || '';
    this.created_ip = data.created_ip || '';
    this.created_id = data.created_id || '';
    this.updated_ip = data.updated_ip || '';
    this.updated_id = data.updated_id || '';
    this.auth_code = data.auth_code || '';
  }
}
